### ISSUE TITLE
[Validation] Database 유저 추가전 사원번호 Unique 확인

### ISSUE THREAD

**Issue by likebullet86** [reiple/Collab#30]
우선순위가 높지는 않으며,

추후 가능하시다면,Database 유저 추가전 사원번호 Unique한 사원 번호인지
확인하는 Secure Code 및 Test Case를 추가하면 좋을것 같습니다.

**Comment by ysk1202** [comment]
public void add(Employee employee)
해당 함수 호출 시 중복 여부 check 예정이며,
search/modify/delete 시 인자로 넘어온 Id를 확인하여 존재 여부를 check 후 후속 처리 하도록 개선하겠습니다.

**Comment by likebullet86** [comment]
구현 확인하였습니다!
