### ISSUE TITLE
[Bug] Command Parser Error

### ISSUE THREAD

**Issue by likebullet86** [reiple/Collab#50]
command Parser 19 line에 HshMap 선언관련하여, 
cannot use <> with anonumous inner classes 에러가 발생합니다!

확인 부탁드립니다.

**Comment by Alphapos7** [comment]
아네 확인하도록 하겠습니다.

**Comment by likebullet86** [comment]
protected static final Map<String, List<String>> SECOND_OPTION_WHITE_MAP = new HashMap<>(){{
->  protected static final Map<String, List<String>> SECOND_OPTION_WHITE_MAP = new HashMap<String, List<String>>(){{

**Comment by Alphapos7** [comment]
에러를 쉽게 수정할수 있었습니다. 감사합니다.
