### ISSUE TITLE
EmployeeDAO, DataBase addItem Interface 확인

### ISSUE THREAD

**Issue by likebullet86** [reiple/Collab#61]
현재 EmployeeDAO의 addItem()은 input으로 Employee item을 사용하고 
DataBase의 addEmpoyee는 List<String> employee를 사용하고 있습니다.

두 객체가 인터페이스를 통일해야 할것 같습니다

**Comment by Alphapos7** [comment]
해당 부분은 김영상님께서 IDAO 와 EmployeeDAO 간에 sync 를 맞춰 주시면 좋을것 같습니다.

**Comment by likebullet86** [comment]
[Sytle] IF에 맞게 수정, Option1/2 전달 방식 및 Update Column별 객체화 필요 #43 PR에 반영되었네요

이슈 닫겠습니다.
