### ISSUE TITLE
Search Testcase 에러

### ISSUE THREAD

**Issue by Alphapos7** [reiple/Collab#64]
IDAO 로 변경하면서 기존 DatabaseDAO 사용한 Testcase 들에 에러가 있는것 같습니다. 확인해주시면 감사 드리겠습니다.

**Comment by ysk1202** [comment]
유효성 검사에서 INPUT이 PASS되지 않아 Exception 발생한 건입니다.
https://github.com/reiple/Collab/pull/67
수정 후 MERGE 요청드립니다.

**Comment by reiple** [comment]
IDAO로 변경하면서 인터페이스가 안 맞게 되었네요.
일단은 employeeDAO로 전달하던 인자들을 (EmployeeDAO)로 type 변환해서 넘기도록 해야겠습니다.


```java
 public String executeCommand(IDAO employeeDAO) {

        if(getSecondOption() instanceof NoneSecondOption) {
            return getSearchName((EmployeeDAO) employeeDAO);
```
