### ISSUE TITLE
[Refactoring] Second Option Class Refactoring

### ISSUE THREAD

**Issue by likebullet86** [reiple/Collab#75]
Search 관련 DayOfBirthdayOption, FirstNameOption, LastNameOption, LastPhoneNumberOption, MiddlePhoneNumberOption
, MothOfBirthdayOption, YearOfbirthdayOption 작동이 거의 유사한듯합니다.

AbstractSecondOption 
 abstract public List<Employee> getFilteredList(EmployeeDAO DAO); -> abstract public List<Employee> getFilteredList(EmployeeDAO DAO, Excutable excutable);
로 lambda함수를 받아서 처리해서 파일을 통합하느건 어떨지 문의드립니다.

**Comment by reiple** [comment]
네. 기능은 거의 동일해서 공통 코드가 있으면 좋겠다는 생각은 했습니다.
이 부분도 이름으로 DAO를 통해서 호출되는 메소드만 차이가 있을 뿐, 형식은 거의 유사한 것 같습니다.
Employee에서 Validation 체크를 하기 때문에 함수 이름으로 해당 부분을 치환 할 수 있으면 좋을 것 같아요.

지금 lambda 함수로 되어 있는 부분은 임시 구현이라서, 실제로 Lambda 처리는 DataBase 클래스에서 되어야 할 것 같습니다.

**Comment by Alphapos7** [comment]
아네 이 부분은 고민해 봤는데, 결국에는 Executable 이 cmd 내부에서 if 문으로 분기를 타는 것을 막기 위해서 객체 상속으로 처리하였습니다. Search option 이 새롭게 추가 되었을떄 현재 구조에서는 class 를 추가하고 앞에서 injection 만 해주면 되는데 어떻게 생각하시나요?

**Comment by Alphapos7** [comment]
개인적으로는 Name, Birthday, PhoneNumber 관련된 option 으로 묶고 각 함수가 적절하게 동작하는것도 괜찮아 보입니다.
