### ISSUE TITLE
[Refactoring] executeCommand String 결과의 개행 문자

### ISSUE THREAD

**Issue by Alphapos7** [reiple/Collab#83]
https://github.com/reiple/Collab/blob/main/src/main/java/collab/EmployeeManager.java#L28

해당 Line 의 executeCommand 를 실행 시 ADD 는 "" string 을 출력하고 나머지 CMD 들은 마지막에 \n 을 붙이면 instance 체크를 안해도 괜찮을 것 같은데 어떻게 생각하시느지 궁금 합니다.

**Comment by reiple** [comment]
이 부분 제가 수정했는데 버그가 있네요.
AddCommand는 실행을 안하는 것 같아요.
